package br.com.tegasistemas.documentofiscal.transformers;

import br.com.tegasistemas.documentofiscal.cte200.classes.*;
import br.com.tegasistemas.documentofiscal.cte200.transformers.*;
import br.com.tegasistemas.documentofiscal.cte200.transformers.CTModalTransformer;
import br.com.tegasistemas.documentofiscal.cte200.transformers.CTTipoDocumentoTransporteAnteriorTransformer;
import br.com.tegasistemas.documentofiscal.cte200.transformers.CTTipoEmissaoTransformer;
import br.com.tegasistemas.documentofiscal.cte200.transformers.CTTipoServicoTransformer;
import br.com.tegasistemas.documentofiscal.cte200.transformers.CTTipoUnidadeCargaTransformer;
import br.com.tegasistemas.documentofiscal.cte200.transformers.CTTipoUnidadeTransporteTransformer;
import br.com.tegasistemas.documentofiscal.cte200.transformers.CTTomadorServicoTransformer;
import br.com.tegasistemas.documentofiscal.cte200.transformers.CTUnidadeMedidaTransformer;
import br.com.tegasistemas.documentofiscal.cte300.classes.*;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTModal;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTTipoDocumentoTransporteAnterior;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTTipoEmissao;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTTipoImpressao;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTTipoServico;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTTipoUnidadeCarga;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTTipoUnidadeTransporte;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTTomadorServico;
import br.com.tegasistemas.documentofiscal.cte300.classes.CTUnidadeMedida;
import br.com.tegasistemas.documentofiscal.nfe310.classes.NFFormaPagamentoPrazo;
import br.com.tegasistemas.documentofiscal.nfe310.classes.lote.envio.NFLoteIndicadorProcessamento;
import br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFFormaPagamentoMoeda;

import br.com.tegasistemas.documentofiscal.cte300.transformes.*;
import br.com.tegasistemas.documentofiscal.mdfe3.classes.def.*;
import br.com.tegasistemas.documentofiscal.mdfe3.transformers.*;

import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFFormaImportacaoIntermediacaoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFFormaPagamentoMoedaTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFFormaPagamentoTransformer;
import br.com.tegasistemas.documentofiscal.nfe400.classes.*;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFIdentificadorLocalDestinoOperacaoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFIndicadorContribuinteCTTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFIndicadorContribuinteNFeTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFIndicadorIEDestinatarioTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFIndicadorPresencaCompradorTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFLoteIndicadorProcessamentoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFModalidadeFreteTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoCombustivelTipoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoEspecieVeiculoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoImpostoTributacaoICMSTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoItemIndicadorExigibilidadeISSTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoItemIndicadorIncentivoFiscalTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoItemProdutoArmamentoTipoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoItemProdutoVeiculoCondicaoChassiTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoItemProdutoVeiculoCondicaoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoItemProdutoVeiculoRestricaoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoItemProdutoVeiculoTipoOperacaoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoRegimeEspecialTributacaoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoSituacaoTributariaCOFINSTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoSituacaoTributariaIPITransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoSituacaoTributariaPISTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoTipoVeiculoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaInfoVeiculoCorTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaMotivoDesoneracaoICMSTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFNotaSituacaoOperacionalSimplesNacionalTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFOperacaoConsumidorFinalTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFOperadoraCartaoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFOrigemProcessoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFProdutoCompoeValorNotaTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFProgramaEmissorTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFRegimeTributarioTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFSituacaoContribuinteTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFTipoImpressaoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFTipoIntegracaoPagamentoTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFViaTransporteInternacionalTransformer;
import br.com.tegasistemas.documentofiscal.nfe310.transformers.NFnotaInfoItemModalidadeBCICMSSTTransformer;
import br.com.tegasistemas.documentofiscal.nfe400.classes.NFIndicadorFormaPagamento;
import br.com.tegasistemas.documentofiscal.nfe400.classes.NFSituacao;
import br.com.tegasistemas.documentofiscal.nfe400.classes.cadastro.NFIndicadorContribuinteCTe;
import br.com.tegasistemas.documentofiscal.nfe400.classes.cadastro.NFIndicadorContribuinteNFe;
import br.com.tegasistemas.documentofiscal.nfe400.classes.cadastro.NFSituacaoContribuinte;
import br.com.tegasistemas.documentofiscal.nfe400.classes.nota.*;
import br.com.tegasistemas.documentofiscal.nfe400.transformers.*;
import br.com.tegasistemas.documentofiscal.DFAmbiente;
import br.com.tegasistemas.documentofiscal.DFModelo;
import br.com.tegasistemas.documentofiscal.DFPais;
import br.com.tegasistemas.documentofiscal.DFUnidadeFederativa;
import br.com.tegasistemas.documentofiscal.nfe400.classes.nota.NFIndicadorEscalaRelevante;
import br.com.tegasistemas.documentofiscal.nfe400.classes.nota.NFMeioPagamento;

import br.com.tegasistemas.documentofiscal.nfe.NFTipoEmissao;
import br.com.tegasistemas.documentofiscal.nfe.transformers.NFTipoEmissaoTransformer;

import br.com.tegasistemas.documentofiscal.nfe400.transformers.NFFinalidadeTransformer;
import br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoItemModalidadeBCICMSTransformer;
import br.com.tegasistemas.documentofiscal.nfe400.transformers.NFOrigemTransformer;
import br.com.tegasistemas.documentofiscal.nfe400.transformers.NFTipoTransformer;
import org.simpleframework.xml.transform.RegistryMatcher;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZonedDateTime;

public class DFRegistryMatcher extends RegistryMatcher {

    public DFRegistryMatcher() {
        super.bind(DFModelo.class, new DFModeloTransformer());
        super.bind(DFAmbiente.class, new DFAmbienteTransformer());
        super.bind(LocalDate.class, new DFLocalDateTransformer());
        super.bind(LocalTime.class, new DFLocalTimeTransformer());
        super.bind(ZonedDateTime.class, new DFDateTimeTransformer());
        super.bind(LocalDateTime.class, new DFLocalDateTimeTransformer());
        super.bind(ZonedDateTime.class, new DFZonedDateTimeTransformer());
        super.bind(DFUnidadeFederativa.class, new DFUnidadeFederativaTransformer());
        super.bind(NFTipoEmissao.class, new NFTipoEmissaoTransformer());
        super.bind(DFPais.class, new DFPaisTransformer());

        // NFE 3.10
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFTipo.class, new NFTipoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFOrigem.class, new NFOrigemTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFFinalidade.class, new NFFinalidadeTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFTipoImpressao.class, new NFTipoImpressaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFOrigemProcesso.class, new NFOrigemProcessoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFOperadoraCartao.class, new NFOperadoraCartaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFProcessoEmissor.class, new NFProgramaEmissorTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFModalidadeFrete.class, new NFModalidadeFreteTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFRegimeTributario.class, new NFRegimeTributarioTransformer());
        super.bind(NFFormaPagamentoPrazo.class, new NFFormaPagamentoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoVeiculoCor.class, new NFNotaInfoVeiculoCorTransformer());
        super.bind(NFFormaPagamentoMoeda.class, new NFFormaPagamentoMoedaTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoTipoVeiculo.class, new NFNotaInfoTipoVeiculoTransformer());
        super.bind(NFSituacaoContribuinte.class, new NFSituacaoContribuinteTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoEspecieVeiculo.class, new NFNotaInfoEspecieVeiculoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFProdutoCompoeValorNota.class, new NFProdutoCompoeValorNotaTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFTipoIntegracaoPagamento.class, new NFTipoIntegracaoPagamentoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFIndicadorIEDestinatario.class, new NFIndicadorIEDestinatarioTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFOperacaoConsumidorFinal.class, new NFOperacaoConsumidorFinalTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoCombustivelTipo.class, new NFNotaInfoCombustivelTipoTransformer());
        super.bind(NFIndicadorContribuinteCTe.class, new NFIndicadorContribuinteCTTransformer());
        super.bind(NFIndicadorContribuinteNFe.class, new NFIndicadorContribuinteNFeTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaMotivoDesoneracaoICMS.class, new NFNotaMotivoDesoneracaoICMSTransformer());
        super.bind(NFLoteIndicadorProcessamento.class, new NFLoteIndicadorProcessamentoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFViaTransporteInternacional.class, new NFViaTransporteInternacionalTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFIndicadorPresencaComprador.class, new NFIndicadorPresencaCompradorTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFFormaImportacaoIntermediacao.class, new NFFormaImportacaoIntermediacaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoImpostoTributacaoICMS.class, new NFNotaInfoImpostoTributacaoICMSTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoSituacaoTributariaIPI.class, new NFNotaInfoSituacaoTributariaIPITransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoSituacaoTributariaPIS.class, new NFNotaInfoSituacaoTributariaPISTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoItemModalidadeBCICMSST.class, new NFnotaInfoItemModalidadeBCICMSSTTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFNotaInfoRegimeEspecialTributacao.class, new NFNotaInfoRegimeEspecialTributacaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoSituacaoTributariaCOFINS.class, new NFNotaInfoSituacaoTributariaCOFINSTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoItemProdutoArmamentoTipo.class, new NFNotaInfoItemProdutoArmamentoTipoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFIdentificadorLocalDestinoOperacao.class, new NFIdentificadorLocalDestinoOperacaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoItemProdutoVeiculoCondicao.class, new NFNotaInfoItemProdutoVeiculoCondicaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoItemProdutoVeiculoRestricao.class, new NFNotaInfoItemProdutoVeiculoRestricaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFNotaInfoItemIndicadorIncentivoFiscal.class, new NFNotaInfoItemIndicadorIncentivoFiscalTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.nota.NFNotaInfoItemIndicadorExigibilidadeISS.class, new NFNotaInfoItemIndicadorExigibilidadeISSTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaSituacaoOperacionalSimplesNacional.class, new NFNotaSituacaoOperacionalSimplesNacionalTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoItemProdutoVeiculoTipoOperacao.class, new NFNotaInfoItemProdutoVeiculoTipoOperacaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoItemProdutoVeiculoCondicaoChassi.class, new NFNotaInfoItemProdutoVeiculoCondicaoChassiTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe310.classes.NFNotaInfoItemModalidadeBCICMS.class, new NFNotaInfoItemModalidadeBCICMSTransformer());

        // NFE 4.00
        super.bind(NFTipo.class, new NFTipoTransformer());
        super.bind(NFOrigem.class, new NFOrigemTransformer());
        super.bind(NFSituacao.class, new NFSituacaoTransformer());
        super.bind(NFFinalidade.class, new NFFinalidadeTransformer());
        super.bind(NFTipoImpressao.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFTipoImpressaoTransformer());
        super.bind(NFOrigemProcesso.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFOrigemProcessoTransformer());
        super.bind(NFOperadoraCartao.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFOperadoraCartaoTransformer());
        super.bind(NFProcessoEmissor.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFProgramaEmissorTransformer());
        super.bind(NFModalidadeFrete.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFModalidadeFreteTransformer());
        super.bind(NFRegimeTributario.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFRegimeTributarioTransformer());
        super.bind(NFNotaInfoVeiculoCor.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoVeiculoCorTransformer());
        super.bind(NFMeioPagamento.class, new NFMeioPagamentoTransformer());
        super.bind(NFIndicadorFormaPagamento.class, new NFIndicadorFormaPagamentoTransformer());
        super.bind(NFNotaInfoTipoVeiculo.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoTipoVeiculoTransformer());
        super.bind(NFSituacaoContribuinte.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFSituacaoContribuinteTransformer());
        super.bind(NFNotaInfoEspecieVeiculo.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoEspecieVeiculoTransformer());
        super.bind(NFProdutoCompoeValorNota.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFProdutoCompoeValorNotaTransformer());
        super.bind(NFTipoIntegracaoPagamento.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFTipoIntegracaoPagamentoTransformer());
        super.bind(NFIndicadorIEDestinatario.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFIndicadorIEDestinatarioTransformer());
        super.bind(NFOperacaoConsumidorFinal.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFOperacaoConsumidorFinalTransformer());
        super.bind(NFNotaInfoCombustivelTipo.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoCombustivelTipoTransformer());
        super.bind(NFIndicadorContribuinteCTe.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFIndicadorContribuinteCTTransformer());
        super.bind(NFIndicadorContribuinteNFe.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFIndicadorContribuinteNFeTransformer());
        super.bind(NFNotaMotivoDesoneracaoICMS.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaMotivoDesoneracaoICMSTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.nfe400.classes.lote.envio.NFLoteIndicadorProcessamento.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFLoteIndicadorProcessamentoTransformer());
        super.bind(NFViaTransporteInternacional.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFViaTransporteInternacionalTransformer());
        super.bind(NFIndicadorPresencaComprador.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFIndicadorPresencaCompradorTransformer());
        super.bind(NFFormaImportacaoIntermediacao.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFFormaImportacaoIntermediacaoTransformer());
        super.bind(NFIndicadorEscalaRelevante.class, new NFIndicadorEscalaRelevanteTransformer());
        super.bind(NFNotaInfoImpostoTributacaoICMS.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoImpostoTributacaoICMSTransformer());
        super.bind(NFNotaInfoSituacaoTributariaIPI.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoSituacaoTributariaIPITransformer());
        super.bind(NFNotaInfoSituacaoTributariaPIS.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoSituacaoTributariaPISTransformer());
        super.bind(NFNotaInfoItemModalidadeBCICMSST.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFnotaInfoItemModalidadeBCICMSSTTransformer());
        super.bind(NFNotaInfoRegimeEspecialTributacao.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoRegimeEspecialTributacaoTransformer());
        super.bind(NFNotaInfoSituacaoTributariaCOFINS.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoSituacaoTributariaCOFINSTransformer());
        super.bind(NFNotaInfoItemProdutoArmamentoTipo.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoItemProdutoArmamentoTipoTransformer());
        super.bind(NFIdentificadorLocalDestinoOperacao.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFIdentificadorLocalDestinoOperacaoTransformer());
        super.bind(NFNotaInfoItemProdutoVeiculoCondicao.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoItemProdutoVeiculoCondicaoTransformer());
        super.bind(NFNotaInfoItemProdutoVeiculoRestricao.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoItemProdutoVeiculoRestricaoTransformer());
        super.bind(NFNotaInfoItemIndicadorIncentivoFiscal.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoItemIndicadorIncentivoFiscalTransformer());
        super.bind(NFNotaInfoItemIndicadorExigibilidadeISS.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoItemIndicadorExigibilidadeISSTransformer());
        super.bind(NFNotaSituacaoOperacionalSimplesNacional.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaSituacaoOperacionalSimplesNacionalTransformer());
        super.bind(NFNotaInfoItemProdutoVeiculoTipoOperacao.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoItemProdutoVeiculoTipoOperacaoTransformer());
        super.bind(NFNotaInfoItemProdutoVeiculoCondicaoChassi.class, new br.com.tegasistemas.documentofiscal.nfe400.transformers.NFNotaInfoItemProdutoVeiculoCondicaoChassiTransformer());
        super.bind(NFNotaInfoItemModalidadeBCICMS.class, new NFNotaInfoItemModalidadeBCICMSTransformer());

        // CTe
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTModal.class, new CTModalTransformer());
        super.bind(CTTipoCte.class, new CTTipoCteTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTTipoServico.class, new CTTipoServicoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTTipoEmissao.class, new CTTipoEmissaoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTUnidadeMedida.class, new CTUnidadeMedidaTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTTipoImpressao.class, new CTTipoImpressaoTransformer());
        super.bind(CTFormaPagamento.class, new CTFormaPagamentoTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTTomadorServico.class, new CTTomadorServicoTransformer());
        super.bind(CTTipoEntregaData.class, new CTTipoEntregaDataTransformer());
        super.bind(CTRetiraMercadoria.class, new CTRetiraMercadoriaTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTTipoUnidadeCarga.class, new CTTipoUnidadeCargaTransformer());
        super.bind(CTResponsavelSeguro.class, new CTResponsavelSeguroTransformer());
        super.bind(CTTipoDocumentoOutro.class, new CTTipoDocumentoOutroTransformer());
        super.bind(CTTipoEntregaHorario.class, new CTTipoEntregaHorarioTransformer());
        super.bind(CTIdentificadorEmissor.class, new CTIdentificadorEmissorTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTTipoUnidadeTransporte.class, new CTTipoUnidadeTransporteTransformer());
        super.bind(br.com.tegasistemas.documentofiscal.cte200.classes.CTTipoDocumentoTransporteAnterior.class, new CTTipoDocumentoTransporteAnteriorTransformer());

        // CTe 300
        super.bind(CTTipoEmissao.class, new br.com.tegasistemas.documentofiscal.cte300.transformes.CTTipoEmissaoTransformer());
        super.bind(CTFinalidade.class, new CTFinalidadeTransformes());
        super.bind(CTProcessoEmissao.class, new CTProcessoEmissaoTransformer());
        super.bind(CTModal.class, new br.com.tegasistemas.documentofiscal.cte300.transformes.CTModalTransformer());
        super.bind(CTTipoServico.class, new br.com.tegasistemas.documentofiscal.cte300.transformes.CTTipoServicoTransformer());
        super.bind(CTRetirada.class, new CTRetiradaTransformer());
        super.bind(CTIndicadorTomador.class, new CTIndicadorTomadorTransformer());
        super.bind(CTTipoImpressao.class, new CTTipoImpressaoTransformes());
        super.bind(CTTomadorServico.class, new br.com.tegasistemas.documentofiscal.cte300.transformes.CTTomadorServicoTransformer());
        super.bind(CTTipoPrazoDataEntrega.class, new CTTipoPrazoDataEntregaTransformer());
        super.bind(CTTipoPrazoHoraEntrega.class, new CTTipoPrazoHoraEntregaTransformer());
        super.bind(CTUnidadeMedida.class, new br.com.tegasistemas.documentofiscal.cte300.transformes.CTUnidadeMedidaTransformer());
        super.bind(CTModeloNF.class, new CTModeloNFTransformer());
        super.bind(CTTipoUnidadeCarga.class, new br.com.tegasistemas.documentofiscal.cte300.transformes.CTTipoUnidadeCargaTransformer());
        super.bind(CTTipoUnidadeTransporte.class, new br.com.tegasistemas.documentofiscal.cte300.transformes.CTTipoUnidadeTransporteTransformer());
        super.bind(CTTipoDocumento.class, new CTTipoDocumentoTransformer());
        super.bind(CTTipoDocumentoTransporteAnterior.class, new br.com.tegasistemas.documentofiscal.cte300.transformes.CTTipoDocumentoTransporteAnteriorTransformer());
        super.bind(CTCodigoSituacaoTributariaICMS.class, new CTCodigoSituacaoTributariaICMSTransformer());
        super.bind(CTInformacoesManuseio.class, new CTInformacoesManuseioTransformer());
        super.bind(CTClasseTarifa.class, new CTClasseTarifaTransformer());
        super.bind(CTUnidadeMedidaProdPerigosos.class, new CTUnidadeMedidaProdPerigososTransformer());
        super.bind(CTTipoDirecao.class, new CTTipoDirecaoTransformer());
        super.bind(CTTipoTrafego.class, new CTTipoTrafegoTransformer());
        super.bind(CTTipoFerrovia.class, new CTTipoFerroviaTransformer());
        super.bind(CTIndicadoNegociavel.class, new CTIndicadoNegociavelTransformer());

        // MDF-e
        super.bind(MDFModalidadeTransporte.class, new MDFModalidadeTransporteTransformer());
        super.bind(MDFProcessoEmissao.class, new MDFProcessoEmissaoTransformer());
        super.bind(MDFTipoCarroceria.class, new MDFTipoCarroceriaTransformer());
        super.bind(MDFTipoEmissao.class, new MDFTipoEmissaoTransformer());
        super.bind(MDFTipoEmitente.class, new MDFTipoEmitenteTransformer());
        super.bind(MDFTipoProprietario.class, new MDFTipoProprietarioTransformer());
        super.bind(MDFTipoRodado.class, new MDFTipoRodadoTransformer());
        super.bind(MDFTipoTranportador.class, new MDFTipoTranportadorTransformer());
        super.bind(MDFTipoUnidadeCarga.class, new MDFTipoUnidadeCargaTransformer());
        super.bind(MDFTipoUnidadeTransporte.class, new MDFTipoUnidadeTransporteTransformer());
        super.bind(MDFUnidadeMedidaPesoBrutoCarga.class, new MDFUnidadeMedidaPesoBrutoCargaTransformer());
        super.bind(MDFTipoResponsavelSeguro.class, new MDFTipoResponsavelSeguroTransformer());
    }
}